// File generated by FlutterFire CLI.
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── WEB ─────────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your key',
    authDomain: 'ur Domain',
    projectId: 'Your id',
    storageBucket: 'YOUR',
    messagingSenderId: 'YOUR',
    appId: 'YOUR',
  );

  // ─── ANDROID ─────────────────────────────────────────────────────────────────
  // Get google-services.json from Firebase Console → Project Settings → Android app
  // Then run: flutterfire configure  to auto-fill these values
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '404109516704',
    projectId: 'YOUR',
    storageBucket: YOUR',
  );

  // ─── iOS ─────────────────────────────────────────────────────────────────────
  // Get GoogleService-Info.plist from Firebase Console → Project Settings → iOS app
  // Then run: flutterfire configure  to auto-fill these values
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR',
    projectId: 'YOUR',
    storageBucket: 'YOUR',
    iosBundleId: 'YOUR,
  );

  // ─── WINDOWS ─────────────────────────────────────────────────────────────────
  // Windows uses the same config as web
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR',
    authDomain: 'YOUR',
    projectId: 'YOUR',
    storageBucket: 'YOUR',
    messagingSenderId: 'YOUR',
    appId: 'YOUR',
  );
}
