// File generated by FlutterFire CLI.
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── WEB ─────────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWGDX-RYOHglbz4Ft11mfR7I1fHxUgOu0',
    authDomain: 'my-notes-app-bcec4.firebaseapp.com',
    projectId: 'my-notes-app-bcec4',
    storageBucket: 'my-notes-app-bcec4.firebasestorage.app',
    messagingSenderId: '404109516704',
    appId: '1:404109516704:web:25341e26b6bc884f3b4ec5',
  );

  // ─── ANDROID ─────────────────────────────────────────────────────────────────
  // Get google-services.json from Firebase Console → Project Settings → Android app
  // Then run: flutterfire configure  to auto-fill these values
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: '404109516704',
    projectId: 'my-notes-app-bcec4',
    storageBucket: 'my-notes-app-bcec4.firebasestorage.app',
  );

  // ─── iOS ─────────────────────────────────────────────────────────────────────
  // Get GoogleService-Info.plist from Firebase Console → Project Settings → iOS app
  // Then run: flutterfire configure  to auto-fill these values
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '404109516704',
    projectId: 'my-notes-app-bcec4',
    storageBucket: 'my-notes-app-bcec4.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotesApp',
  );

  // ─── WINDOWS ─────────────────────────────────────────────────────────────────
  // Windows uses the same config as web
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWGDX-RYOHglbz4Ft11mfR7I1fHxUgOu0',
    authDomain: 'my-notes-app-bcec4.firebaseapp.com',
    projectId: 'my-notes-app-bcec4',
    storageBucket: 'my-notes-app-bcec4.firebasestorage.app',
    messagingSenderId: '404109516704',
    appId: '1:404109516704:web:25341e26b6bc884f3b4ec5',
  );
}